services:
  loltrains:
    container_name: loltrains-tg
    build: .
    ports:
      - 8081:8000
    volumes:
      - /var/www/loltrains-tg/data:/app/data
    env_file:
      - /var/www/loltrains-tg/.env
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true