services:
  loltrains-bot:
    container_name: loltrains-bot
    build: .
    ports:
      - 8081:8000
    volumes:
      - /var/www/loltrains-bot/data:/app/data
    env_file:
      - /var/www/loltrains-bot/.env
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true